name: arcore_flutter_plugin_example
description: Demonstrates how to use the arcore_flutter_plugin plugin and develop AR Flutter Android Apps
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  arcore_flutter_plugin:
    path: ../
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - items/